import * as THREE from "three";

function verticesFor(mesh: THREE.Mesh) {
  const geometry = mesh.geometry as THREE.BufferGeometry;
  const position = geometry.getAttribute("position");
  const index = geometry.getIndex();
  const vertices: number[] = [];
  for (let i = 0; i < position.count; i++) vertices.push(position.getX(i), position.getY(i), position.getZ(i));
  const polygons: number[] = [];
  if (index) {
    for (let i = 0; i < index.count; i += 3) polygons.push(index.getX(i), index.getX(i + 1), -(index.getX(i + 2) + 1));
  } else {
    for (let i = 0; i < position.count; i += 3) polygons.push(i, i + 1, -(i + 2 + 1));
  }
  return { vertices, polygons };
}

export function exportAsciiFbx(root: THREE.Object3D) {
  let modelId = 100000;
  let geometryId = 200000;
  const objects: string[] = [];
  const connections: string[] = [];
  root.updateMatrixWorld(true);
  root.traverse(object => {
    if (!(object instanceof THREE.Mesh)) return;
    const { vertices, polygons } = verticesFor(object);
    const geoId = geometryId++;
    const model = modelId++;
    const safeName = (object.name || "Mesh").replace(/[^a-zA-Z0-9_]/g, "_");
    objects.push(`\tGeometry: ${geoId}, \"Geometry::${safeName}\", \"Mesh\" {\n\t\tVertices: ${vertices.join(",")}\n\t\tPolygonVertexIndex: ${polygons.join(",")}\n\t}`);
    const position = new THREE.Vector3(); const rotation = new THREE.Euler(); const scale = new THREE.Vector3();
    object.matrixWorld.decompose(position, new THREE.Quaternion().setFromEuler(rotation), scale);
    objects.push(`\tModel: ${model}, \"Model::${safeName}\", \"Mesh\" {\n\t\tVersion: 232\n\t\tProperties70:  {\n\t\t\tP: \"Lcl Translation\", \"Lcl Translation\", \"A+\", \"A\",${position.x},${position.y},${position.z}\n\t\t\tP: \"Lcl Scaling\", \"Lcl Scaling\", \"A+\", \"A\",${scale.x},${scale.y},${scale.z}\n\t\t}\n\t}`);
    connections.push(`\tC: \"OO\",${geoId},${model}`);
    connections.push(`\tC: \"OO\",${model},0`);
  });
  return `; FBX 7.4.0 project file\n; Generated by Forge 3D AI\nFBXHeaderExtension:  {\n\tFBXHeaderVersion: 1003\n\tFBXVersion: 7400\n\tCreator: \"Forge 3D AI\"\n}\nDefinitions:  {\n\tVersion: 100\n\tCount: ${objects.length}\n}\nObjects:  {\n${objects.join("\n")}\n}\nConnections:  {\n${connections.join("\n")}\n}\n`;
}
