import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef, useState } from "react";
import { Canvas } from "@react-three/fiber";
import { Environment, Grid, OrbitControls, PerspectiveCamera, Sky, TransformControls, useGLTF } from "@react-three/drei";
import { GLTFExporter } from "three/examples/jsm/exporters/GLTFExporter.js";
import { OBJExporter } from "three/examples/jsm/exporters/OBJExporter.js";
import * as THREE from "three";
import { exportAsciiFbx } from "./fbxExporter";
import { createZip } from "./zip";
import { Box, Crosshair, Download, Eye, EyeOff, Focus, Move3D, Rotate3D, Scaling, SlidersHorizontal, SquareDashedMousePointer } from "lucide-react";
import { Button } from "@/components/ui/button";

export type TransformMode = "translate" | "rotate" | "scale";
export type ExportFormat = "glb" | "obj" | "fbx";
export type CameraPreset = "front" | "top" | "side";
export type ForgeViewportHandle = { export: (format: ExportFormat) => Promise<void>; exportPackage: (format: "obj" | "fbx") => Promise<void>; focusObject: () => void; focusSelection: () => void; frameAll: () => void; setCameraPreset: (preset: CameraPreset) => void; setTransform: (kind: "position" | "rotation" | "scale", axis: "x" | "y" | "z", value: number) => void };

type Props = { wireframe: boolean; lightPower: number; materialColor: string; environment: "studio" | "sunset" | "night"; importedUrl?: string; showRig?: boolean; animationPlaying?: boolean; animationTimeScale?: number; onSelectionChange?: (name: string, object?: THREE.Object3D, objects?: THREE.Object3D[]) => void; onTransformChange?: (object?: THREE.Object3D) => void; transformMode?: TransformMode };
type SceneState = { selected: string; selectedObject?: THREE.Object3D; selectedObjects: THREE.Object3D[]; mode: TransformMode; visible: boolean; showOutliner: boolean; setSelected: (value: string) => void; setSelectedObject: (value: THREE.Object3D) => void; setSelectedObjects: (value: THREE.Object3D[]) => void; setMode: (value: TransformMode) => void; setVisible: (value: boolean) => void; setShowOutliner: (value: boolean) => void; onTransformChange?: (object?: THREE.Object3D) => void; onSelectionChange?: (name: string, object?: THREE.Object3D, objects?: THREE.Object3D[]) => void };

function SceneContent({ wireframe, importedUrl, showRig, animationPlaying, animationTimeScale, scene }: Pick<Props, "wireframe" | "importedUrl" | "showRig" | "animationPlaying" | "animationTimeScale"> & { scene: SceneState }) {
  const selectionPivot = useRef<THREE.Group>(null);
  useEffect(() => { if (selectionPivot.current && scene.selectedObjects.length) { const center = new THREE.Vector3(); scene.selectedObjects.forEach(object => center.add(object.getWorldPosition(new THREE.Vector3()))); center.multiplyScalar(1 / scene.selectedObjects.length); selectionPivot.current.position.copy(center); } }, [scene.selectedObjects]);
  const select = (event: { stopPropagation: () => void; object?: THREE.Object3D; shiftKey?: boolean; ctrlKey?: boolean; metaKey?: boolean }, name: string) => { event.stopPropagation(); const object = event.object; if (!object) return; const additive = Boolean(event.shiftKey || event.ctrlKey || event.metaKey); const next = additive ? (scene.selectedObjects.some(item => item === object) ? scene.selectedObjects.filter(item => item !== object) : [...scene.selectedObjects, object]) : [object]; scene.setSelectedObjects(next); scene.setSelected(name); scene.setSelectedObject(next[0] ?? object); scene.onSelectionChange?.(next.length > 1 ? `${name} +${next.length - 1}` : name, next[0] ?? object, next); };
  return <group>
    {importedUrl ? <ImportedModel url={importedUrl} showRig={showRig} animationPlaying={animationPlaying} animationTimeScale={animationTimeScale} onSelect={event => select(event, "Modelo importado")} /> : null}
    {scene.selectedObjects.length > 0 && <TransformControls mode={scene.mode} object={scene.selectedObjects.length > 1 ? selectionPivot.current ?? undefined : scene.selectedObject} size={0.85} onObjectChange={() => scene.onTransformChange?.(scene.selectedObject)} />}
    <group ref={selectionPivot} visible={false} />
  </group>;
}

function ImportedModel({ url, showRig, animationPlaying, animationTimeScale = 1, onSelect }: { url: string; showRig?: boolean; animationPlaying?: boolean; animationTimeScale?: number; onSelect: (event: { stopPropagation: () => void; object?: THREE.Object3D; shiftKey?: boolean; ctrlKey?: boolean; metaKey?: boolean }) => void }) { const { scene, animations } = useGLTF(url); const mixer = useMemo(() => new THREE.AnimationMixer(scene), [scene]); const clips = useMemo(() => animations ?? [], [animations]); const rig = useMemo(() => new THREE.SkeletonHelper(scene), [scene]); useEffect(() => { const actions = clips.map(clip => mixer.clipAction(clip)); if (animationPlaying) actions.forEach(action => { action.reset(); action.play(); }); else actions.forEach(action => action.stop()); actions.forEach(action => { action.timeScale = animationTimeScale; }); return () => actions.forEach(action => action.stop()); }, [animationPlaying, animationTimeScale, clips, mixer]); useEffect(() => { let frame = 0; const tick = (time: number) => { mixer.update(Math.min(time / 1000, 0.05)); frame = requestAnimationFrame(tick); }; if (animationPlaying && clips.length) frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [animationPlaying, clips.length, mixer]); return <group><primitive object={scene} scale={1.6} position={[0, -1.1, 0]} onClick={onSelect} />{showRig && <primitive object={rig} scale={1.6} position={[0, -1.1, 0]} />}</group>; }

function downloadBlob(blob: Blob, filename: string) { const href = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = href; anchor.download = filename; anchor.click(); URL.revokeObjectURL(href); }

async function packageFor(root: THREE.Object3D, format: "obj" | "fbx") {
  const entries: { name: string; data: Uint8Array }[] = [];
  const model = format === "obj" ? new OBJExporter().parse(root) : exportAsciiFbx(root);
  entries.push({ name: `forge-model.${format}`, data: new TextEncoder().encode(model) });
  const materials: string[] = ["# Forge 3D AI materials", "newmtl ForgeMaterial", "Kd 0.65 0.72 0.82", "Ns 32"];
  const textures: string[] = [];
  let textureIndex = 0;
  root.traverse(object => { if (!(object instanceof THREE.Mesh)) return; const material = Array.isArray(object.material) ? object.material[0] : object.material; const map = material && "map" in material ? material.map : undefined; const image = map?.image as { src?: string } | undefined; if (image?.src && !textures.includes(image.src)) { const filename = `textures/texture-${textureIndex++}.png`; textures.push(image.src); materials.push(`map_Kd ${filename}`); } });
  entries.push({ name: "forge-model.mtl", data: new TextEncoder().encode(materials.join("\n") + "\n") });
  for (let index = 0; index < textures.length; index += 1) { try { const response = await fetch(textures[index]); if (response.ok) entries.push({ name: `textures/texture-${index}.png`, data: new Uint8Array(await response.arrayBuffer()) }); } catch { /* textura cross-origin indisponível: manifesto continua válido */ } }
  entries.push({ name: "forge-manifest.json", data: new TextEncoder().encode(JSON.stringify({ format, mesh: true, mtl: true, textures: textures.length, note: "O GLB continua sendo o formato recomendado para preservar UV, materiais, texturas, rigs e animações incorporados." }, null, 2)) });
  return createZip(entries);
}

export const ForgeViewport = forwardRef<ForgeViewportHandle, Props>(function ForgeViewport({ wireframe, lightPower, materialColor: _materialColor, environment, importedUrl, showRig, animationPlaying, animationTimeScale, onSelectionChange, onTransformChange, transformMode }, ref) {
  const [selected, setSelected] = useState("Cena"); const [selectedObject, setSelectedObject] = useState<THREE.Object3D>(); const [selectedObjects, setSelectedObjects] = useState<THREE.Object3D[]>([]); const [mode, setMode] = useState<TransformMode>("translate"); const [visible, setVisible] = useState(true); const [showOutliner, setShowOutliner] = useState(true); const controlsRef = useRef<any>(null); const exportRoot = useRef<THREE.Group | null>(null); const activeMode = transformMode ?? mode;
  const sceneState: SceneState = { selected, selectedObject, selectedObjects, mode: activeMode, visible, showOutliner, setSelected, setSelectedObject, setSelectedObjects, setMode, setVisible, setShowOutliner, onTransformChange, onSelectionChange };
  const fitBounds = (bounds: THREE.Box3, preset?: CameraPreset) => { const controls = controlsRef.current; const camera = controls?.object as THREE.PerspectiveCamera | undefined; if (!controls || !camera || bounds.isEmpty()) return; const center = bounds.getCenter(new THREE.Vector3()); const size = bounds.getSize(new THREE.Vector3()); const distance = Math.max(size.length() * 1.25, 4.2); const direction = preset === "top" ? new THREE.Vector3(0, 1, 0.01) : preset === "side" ? new THREE.Vector3(1, 0.28, 0.01) : new THREE.Vector3(0.55, 0.35, 1); camera.position.copy(center.clone().add(direction.normalize().multiplyScalar(distance))); camera.lookAt(center); controls.target.copy(center); controls.update(); };
  const frameAll = () => { if (exportRoot.current) fitBounds(new THREE.Box3().setFromObject(exportRoot.current)); };
  const focusSelection = () => { if (selectedObjects.length) { const bounds = new THREE.Box3(); selectedObjects.forEach(object => bounds.expandByObject(object)); fitBounds(bounds); } else frameAll(); };
  const focusObject = frameAll;
  const setCameraPreset = (preset: CameraPreset) => { if (exportRoot.current) fitBounds(new THREE.Box3().setFromObject(exportRoot.current), preset); };
  useEffect(() => { const timer = window.setTimeout(frameAll, importedUrl ? 260 : 80); return () => window.clearTimeout(timer); }, [importedUrl]);
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement) return; const key = event.key.toLowerCase(); if (key === "f") focusSelection(); if (key === "a") frameAll(); if (key === "1") setCameraPreset("front"); if (key === "2") setCameraPreset("top"); if (key === "3") setCameraPreset("side"); }; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); });
  useImperativeHandle(ref, () => ({ export: async format => { const source = exportRoot.current; if (!source || !importedUrl) throw new Error("No model in viewport"); if (format === "glb") { const exporter = new GLTFExporter(); const result = await new Promise<ArrayBuffer>((resolve, reject) => exporter.parse(source, value => resolve(value instanceof ArrayBuffer ? value : new TextEncoder().encode(JSON.stringify(value)).buffer), reject, { binary: true })); downloadBlob(new Blob([result], { type: "model/gltf-binary" }), "forge-model.glb"); } else if (format === "obj") downloadBlob(new Blob([new OBJExporter().parse(source)], { type: "text/plain" }), "forge-model.obj"); else downloadBlob(new Blob([exportAsciiFbx(source)], { type: "application/octet-stream" }), "forge-model.fbx"); }, exportPackage: async format => { const source = exportRoot.current; if (!source || !importedUrl) throw new Error("No model in viewport"); downloadBlob(await packageFor(source, format), `forge-model-${format}-package.zip`); }, focusObject, focusSelection, frameAll, setCameraPreset, setTransform: (kind, axis, value) => { const targets = selectedObjects.length ? selectedObjects : selectedObject ? [selectedObject] : []; targets.forEach(object => { object[kind][axis] = value; }); onTransformChange?.(selectedObject); } }), [importedUrl, selectedObject, selectedObjects, onTransformChange]);
  const skyColor = environment === "night" ? "#071225" : environment === "sunset" ? "#3a1d2d" : "#89a7c7";
  return <div className="relative h-full min-h-[680px] w-full overflow-hidden rounded-[1.4rem] border border-white/10 bg-[#0b1017] shadow-2xl shadow-black/30"><Canvas shadows dpr={[1, 1.6]} camera={{ position: [5, 3, 7], fov: 42 }} gl={{ antialias: true }}><color attach="background" args={[skyColor]} /><PerspectiveCamera makeDefault position={[5, 3, 7]} fov={42} /><ambientLight intensity={environment === "night" ? 0.18 : 0.45} /><directionalLight castShadow position={[4, 7, 3]} intensity={lightPower} color="#f2f5ff" shadow-mapSize={[2048, 2048]} /><pointLight position={[-3, 2, 2]} intensity={lightPower * 0.65} color="#b8d8ff" /><Sky distance={450} sunPosition={environment === "night" ? [-1, -0.2, -1] : environment === "sunset" ? [-2, 1, -1] : [4, 5, 2]} inclination={0.48} azimuth={0.25} /><mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -2.05, 0]} receiveShadow><planeGeometry args={[80, 80]} /><meshStandardMaterial color={environment === "night" ? "#101827" : "#283b4d"} roughness={0.92} /></mesh><group ref={exportRoot}><SceneContent wireframe={wireframe} importedUrl={importedUrl} showRig={showRig} animationPlaying={animationPlaying} animationTimeScale={animationTimeScale} scene={sceneState} /></group><Grid args={[40, 40]} cellSize={0.5} cellThickness={0.45} cellColor="#7890a5" sectionSize={5} sectionThickness={0.9} sectionColor="#a9bfd1" fadeDistance={28} infiniteGrid position={[0, -2.02, 0]} /><Environment preset={environment} background={false} /><OrbitControls ref={controlsRef} makeDefault enableDamping dampingFactor={0.08} minDistance={1.5} maxDistance={40} target={[0, -0.4, 0]} /></Canvas>
    <div className="absolute left-4 top-4 flex items-center gap-1 rounded-xl border border-white/15 bg-[#0b1017]/85 p-1.5 shadow-lg backdrop-blur"><Button size="icon" variant="ghost" className={activeMode === "translate" ? "bg-[#d7ff48]/15 text-[#d7ff48]" : "text-white/55"} onClick={() => setMode("translate")} title="G · Move"><Move3D className="h-3.5 w-3.5" /></Button><Button size="icon" variant="ghost" className={activeMode === "rotate" ? "bg-[#d7ff48]/15 text-[#d7ff48]" : "text-white/55"} onClick={() => setMode("rotate")} title="R · Rotate"><Rotate3D className="h-3.5 w-3.5" /></Button><Button size="icon" variant="ghost" className={activeMode === "scale" ? "bg-[#d7ff48]/15 text-[#d7ff48]" : "text-white/55"} onClick={() => setMode("scale")} title="S · Scale"><Scaling className="h-3.5 w-3.5" /></Button><span className="mx-1 h-5 w-px bg-white/15" /><Button size="icon" variant="ghost" className="text-white/55" onClick={() => setShowOutliner(value => !value)} title="Toggle scene"><SlidersHorizontal className="h-3.5 w-3.5" /></Button><Button size="icon" variant="ghost" className="text-white/55" onClick={() => setVisible(value => !value)} title="Toggle visibility">{visible ? <Eye className="h-3.5 w-3.5" /> : <EyeOff className="h-3.5 w-3.5" />}</Button></div>
    <div className="absolute bottom-4 left-4 flex flex-wrap items-center gap-1.5 rounded-xl border border-white/15 bg-[#0b1017]/85 p-2 shadow-lg backdrop-blur"><button onClick={focusSelection} className="camera-action"><Focus className="h-3 w-3" /> Focar seleção <kbd>F</kbd></button><button onClick={frameAll} className="camera-action"><SquareDashedMousePointer className="h-3 w-3" /> Enquadrar tudo <kbd>A</kbd></button><button onClick={() => setCameraPreset("front")} className="camera-action">Frente <kbd>1</kbd></button><button onClick={() => setCameraPreset("top")} className="camera-action">Topo <kbd>2</kbd></button><button onClick={() => setCameraPreset("side")} className="camera-action">Lado <kbd>3</kbd></button></div>
    {showOutliner && <div className="absolute right-4 top-4 w-48 rounded-xl border border-white/15 bg-[#0b1017]/85 p-2 shadow-lg backdrop-blur"><div className="mb-2 flex items-center justify-between px-1 text-[9px] font-bold uppercase tracking-[.18em] text-white/40"><span>Cena {selectedObjects.length > 1 ? `· GRUPO ${selectedObjects.length}` : ""}</span><Box className="h-3 w-3" /></div><button onClick={() => { setSelected("Cena"); setSelectedObjects([]); }} className={`flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-[10px] ${selected === "Cena" ? "bg-[#d7ff48]/10 text-[#d7ff48]" : "text-white/50"}`}><span className="h-1.5 w-1.5 rounded-full bg-white/25" />Cena</button>{importedUrl && <button onClick={() => setSelected("Modelo importado")} className={`flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-[10px] ${selected === "Modelo importado" ? "bg-[#d7ff48]/10 text-[#d7ff48]" : "text-white/50"}`}><span className={`h-1.5 w-1.5 rounded-full ${selected === "Modelo importado" ? "bg-[#d7ff48]" : "bg-white/25"}`} />Modelo importado</button>}{selectedObjects.length > 1 && <div className="mt-2 rounded-lg border border-[#d7ff48]/25 bg-[#d7ff48]/10 px-2 py-2 text-[9px] font-bold uppercase tracking-wider text-[#d7ff48]">Seleção agrupada<br /><span className="font-normal text-white/55">{selectedObjects.length} objetos · transformação em grupo</span></div>}</div>}
    {!importedUrl && <div className="pointer-events-none absolute inset-0 grid place-items-center"><div className="rounded-2xl border border-dashed border-white/20 bg-[#0b1017]/35 px-8 py-6 text-center backdrop-blur-sm"><Box className="mx-auto mb-3 h-8 w-8 text-white/25" /><div className="text-sm font-semibold text-white/55">Seu palco 3D está vazio</div><div className="mt-1 max-w-xs text-xs text-white/30">Gere ou importe um modelo para visualizá-lo no cenário de jogo.</div></div></div>}
    {selected !== "Cena" && <div className="absolute right-4 bottom-20 rounded-lg border border-[#d7ff48]/25 bg-[#0b1017]/85 px-3 py-2 text-[10px] text-white/65 backdrop-blur"><span className="font-bold text-[#d7ff48]">{selectedObjects.length > 1 ? `GRUPO · ${selectedObjects.length} OBJETOS` : selected}</span><span className="mx-2 text-white/20">•</span>{activeMode === "translate" ? "mover" : activeMode === "rotate" ? "rotacionar" : "escalar"}</div>}
    <div className="pointer-events-none absolute right-4 bottom-4 text-[10px] font-semibold uppercase tracking-[.22em] text-white/45">Orbitar · pan · zoom</div>
  </div>;
});
